# Generated by Django 4.2.5 on 2023-11-04 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import knowledgekeep.models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgekeep', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reviewed', models.BooleanField(default=False)),
                ('views', models.IntegerField(default=0)),
                ('paper_name', models.CharField(max_length=255, null=True)),
                ('paper_description', models.TextField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=False)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(help_text='Upload only .pdf files.', upload_to='media/%Y/%m/%d', validators=[knowledgekeep.models.validate_paper_type])),
                ('type', models.CharField(choices=[('journal', 'Journal'), ('article', 'Article')], default='journal', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
