# Generated by Django 4.2.5 on 2023-11-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgekeep', '0003_alter_papers_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subsciption_type',
            field=models.CharField(choices=[('3months', '3 Months'), ('6months', '6 Months'), ('1year', '1 Year')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='papers',
            name='type',
            field=models.CharField(choices=[('financeandeconomics', 'Finance & Economics'), ('mathematicsandstatistics', 'Mathematics and Statictics'), ('environmentalscience', 'Environmental Science'), ('computerscience', 'Computer Science')], default='Finance & Economics', max_length=25),
        ),
    ]
