# Generated by Django 4.2.5 on 2023-11-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgekeep', '0004_userprofile_has_subscribed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='subsciption_type',
            new_name='subscription_type',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscribed_on',
            field=models.DateTimeField(null=True),
        ),
    ]
