# Generated by Django 4.2.5 on 2023-11-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgekeep', '0006_papers_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='subscribed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
